{% set name = "jobdispatcher" %}
{% set version = "0.1.0" %}



package:
  name: "{{ name|lower }}"
  version: "{{ version }}"



source:
  url: https://github.com/GES-compchem/job-dispatcher/archive/refs/tags/0.1.0-alpha.tar.gz




build:
  number: 0



requirements:
  host:
    - python

  run:
    - python



test:
  imports:
    - jobdispatcher



about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file:
  summary: ""
  doc_url:
  dev_url:



extra:
  recipe-maintainers:
    - GES-compchem